// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./../src/components/Block.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    Game: typeof import('./../src/views/Game.vue')['default']
  }
}

export { }
